---
title: "Simulations in Sociology Response Paper"
author: "Sanittawan Nikki Tan"
date: "10/19/2018"
output:
  pdf_document: default
  html_document: default
indent: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In her article *Computer Simulation in Sociology: What Contribution?*, Moretti surveyed four main techniques of simulation that have been used in sociology, namely system dynamics, multiagent systems, cellular automata, and genetic algorithms, and discuss their contribution to sociology. Although computer simulation is a promising method that can be beneficial for many fields in the social sciences, some weaknesses still remain. This paper discusses some of the potential weaknesses of certain methods in simulation, gives an example of the application of dynamic feedback in Sociology and explores future research questions in Political Science. 

As Moretti nicely summarized, the main weakness of a computer simulation regardless of techniques is that the validity of a simulation largely depends on two elements: the validity of the theory that the model is based on and the validity of the computational tools used for such simulation. In other words, if the theory that supports a simulation does not accurately capture the reality, the simulation will not be valid. Take multiagent systems technique as a case in point. Simulations based on multiagent systems are very useful for studying how autonomous agents in a system interact and causes a structure to emerge over time. However, its potential weakness is that such simulation must include "a detailed list of rules of agents' behavior, that is, protocols of communications and decision-making procedures that consider environmental changes and all interactions with other agents in that systems." The model relies on researchers' understanding of these rules and, additionally, accurately model them into the simulation. Moreover, researchers also have to make assumptions regarding an agent in the system; for instance, some models begin from the assumption that an agent is a rational actor. Although this is a fairly standard assumption across many theories in the social sciences and can easily be modeled into a simulation, one may question if an agent is indeed *always* a rational actor. 

Cellular automata technique which is a particular kind of multiagent system may also suffer from similar problems. This is because cellular automata assume that agents in a system have "a specific and determined position in a lattice" and behave and interact homogeneously. What if agents do not act homogeneously? How do we deal with outliers? It seems to me that its strength, which is simplicity, is also its weakness. As Moretti pointed out, cellular automata assume "synchronous updating" as in biology, but individual agents in a society may have a different timeline in "updating" such as developing opinions. Another limitation of cellular automata that the author discussed is the difficulty in defining neighborhood or boundary that individuals in a society interact. This stems from the fact the model establishes that individuals interact solely with a subset of a population. However, in reality, that subset is hard to define taken into account the advent of the internet and technology and that particular subset also changes over time.           

Another problem of simulation validity is that it is difficult to set criteria and measurement for validity. It seems that social scientists who wish to use simulation still have to develop standardized tools or methods for evaluating if a study is valid. Although potential weaknesses discussed so far remain challenges for future research, some models such as system dynamics can still be useful for explaining and discovering relationships in a complex system, especially how an action causes a change in the system which, in turn, causes another change. 

Developed by Jay Forrester of MIT Sloan School of Management in the 1950s, system dynamics is a model for studying complex systems taken into account agents' actions. System dynamics has wide application in Sociology. For example, the model translates conflict theory, which posits that society functions in a way that individuals and their respective groups maximize their benefits which lead to conflicts among groups and eventually social change, propagated by Marx and Weber into a practical simulation. Researchers may use a toolkit such as SWARM developed by the Santa Fe Institute to model how interests groups compete in the policy-making process. An example of sociological models concerning dynamic feedback that Moretti cited is the work of Doran et al. (1994), *The EOS project: Modelling Upper Paleolithic social change*, which sought to understand circumstances that contribute to the formation of hierarchies in a society. Without simulation, it is nearly impossible to recreate the circumstances of the Upper Paleolithic era.      

A potential application of system dynamics in Political Science, especially the feedback loops, leads to many interesting questions. For instance, in International Relations subfield, one may study how the norm of Responsibility to Protect (R2P) emerged from the struggle between civil societies and states and how R2P shapes and changes state behaviors and the concept of sovereignty. The acceptance of R2P, which maintains that every nation has the responsibility to protect all of their citizens regardless of political, racial and religious affiliations to prevent genocide, ethnic cleansing and other human rights violations, at the United Nations is a major milestone because it allows the United Nations and other countries to intervene to stop crimes against humanities in a country. Since R2P clearly weakens the concept of sovereignty, we may be able to use system dynamics to simulate how this change affects behaviors of all states and the international system and if the norm leads to a formation of a group of states that are working on undermining the norm. Another interesting research question could be the study of how increasing the number of immigrant workers or accepting more refugees into a country affects demography and politics. For instance, countries like Japan and Singapore which are facing population problems because there are increasingly fewer young workers may use simulation to understand how increasing the number of immigrant workers can affect the country's demography and eventually politics in the long run. In the short run, one may think that importing workers can solve labor supply shortages in key industries. However, there are potential long-run effects that result from this change in population. Will more immigrant workers who are racially and culturally different from its citizens give rise to a right-wing nationalist party because the country's citizens feel threatened by the potential loss of homogeneity? Or will increased immigrants indeed economically benefit the country by raising productivity level and quality of life and contribute to more multiculturalism? Simulated data and simulation are clearly useful in both cases because policymakers can look at predicted results without implementing the policy if researchers model states and citizens behaviors accurately. Moreover, there are dynamic feedbacks as one change leads to another change in both cases.  

Despite its weaknesses, computer simulation can be applied to various study in the social sciences. Its main strength is that it enables social scientists to simulate the real world without making an impact. In other words, computer simulation makes possible studies that are impossible to do by observational studies and experiments. However, researchers have to pay attention to underlying assumptions and limitations of simulation before generalizing the results.

